---
title: "Learning R (intermediate DDEA R course)"
author: "Emma"
format: html
---

## R setup

```{r setup}
library(tidyverse)
library(here)
library(snakecase)
source(here("R/functions.R"))
```

## Importing new data (15)
to_snake_case makes it more reable, so none of the coloums are in uppercase. 
n_max determines how many row are loaded from this file
```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Exercise: Reading another file (15)

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

```{r}
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

##Bundling code into functions (16)

```{r}
#' Add two number together
#'
#' @param num1 A number here
#' @param num2 A number here
#'
#' @returns Returns the sum of two numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```

## Exercise (16)

```{r}
# Outputs only 100 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read(max_rows = Inf)
```

##Making robust and reusable functions (17)
